targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        options:
          auto_register: true

      retrofit_generator:retrofit:
        enabled: true
        options:
          generate_to_string: true

      json_serializable:json_serializable:
        enabled: true
        options:
          explicit_to_json: true
          include_if_null: false

      hive_generator:hive_generator:
        enabled: true
        options:
          generate_to_string: true

    sources:
      - lib/**
      - test/**
